language: php

# We want to test against PHP 5.3/5.4/5.5
php:
  - 5.5
  - 5.4
  - 5.3

# Separate different test suites
env:
  matrix:
    - TEST_SUITE=PluginTests
    - TEST_SUITE=CoreTests
    - TEST_SUITE=IntegrationTests

# Run PHP 5.4 for aa tests to generate
# code coverage.
matrix:
  include:
    - php: 5.4
      env: TEST_SUITE=

script: ./travis.sh

before_script:
  - mysql -e 'create database piwik_test;'
  - ./tests/travis/prepare.sh
  - ./tests/travis/setup_webserver.sh
  - cd tests/PHPUnit

notifications:
  irc:
    skip_join: true
    on_success: change
    channels:
      - "irc.freenode.org#piwik-dev"
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
  email:
    - piwik-builds@piwik.org
