language: php

# We want to test against 
php:
  - 5.5
  - 5.4
  - 5.3

script: phpunit --configuration phpunit.xml --coverage-text

before_script:
  - mysql -e 'create database piwik_test;'
  - ./tests/travis.sh
  - ./tests/travis/setup_webserver.sh
  - cd tests/PHPUnit

matrix:
  allow_failures:
    - php: 5.5
